### ISSUE TITLE
Cartões salvos não são exibidos logo após o usuário colocar o email

### ISSUE THREAD

**Issue by vibegui** [vtex/front.payment-data#6]
Tem que atualizar a página para serem exibidos.

Also, temos que decidir se vamos escolher o paymentGroup que tem availableAccounts como default caso não venha nenhum pagamento.

@augustocb @brenoc ideas?

**Comment by klzns** [comment]
> Also, temos que decidir se vamos escolher o paymentGroup que tem availableAccounts como default caso não venha nenhum pagamento.

Eu acho que tem que selecionar sim.

**Comment by augustocb** [comment]
quem são availableAccounts?

**Comment by klzns** [comment]
@augustocb cartões salvos

**Comment by vibegui** [comment]
Fixed via 050a3f14ee3ca6d0dca4e9ba2e24258c8b9abce9
